---
title: "R Notebook"
output: html_notebook
---

# Notes

```{r}
source("data_cleaning.R")
```

```{r}
video_game_sales_clean %>% 
  group_by(platform) %>% 
  summarise(mean_sales = mean(global_sales)) %>% 
  ggplot() +
  aes(x = platform, y = mean_sales) +
  geom_col()
```

```{r}
video_game_sales_clean %>% 
  filter(developer != "Nintendo") %>% 
  group_by(platform) %>% 
  summarise(mean_sales = mean(global_sales)) %>% 
  ggplot() +
  aes(x = platform, y = mean_sales) +
  geom_col()
```

```{r}
video_game_sales_clean %>% 
  distinct(year_of_release) %>% 
  arrange(year_of_release)
```

```{r}
video_game_ratings <- video_game_sales %>% 
  filter(user_count > 25) %>% 
  filter(critic_count > 5) %>% 
  mutate(user_score = as.numeric(user_score) * 10) %>% 
  mutate(year_of_release = as.numeric(year_of_release)) %>% 
  mutate(platform = case_when(
    platform %in% nintendo ~ "Nintendo",
    platform %in% xbox ~ "Microsoft Xbox",
    platform %in% playstation ~ "Sony Playstation",
    platform %in% sega ~ "Sega",
    platform %in% other ~ "Other"
  )) %>% 
  pivot_longer(cols = c("critic_score", "user_score"),
               names_to = "critic_or_user", values_to = "score")
```

```{r}
video_game_ratings %>% 
  filter(platform == "PC")
```

```{r}
video_game_sales_clean %>% 
  distinct(publisher) %>% 
  arrange(publisher)
```

```{r}
video_game_sales_clean %>% 
  filter(genre %in% c("Sports")) %>% 
  filter(year_of_release > 1999)
```

```{r}
video_game_sales_clean %>% 
  distinct(rating)
```

